#include <stdio.h>

/*
    Each new term in the Fibonacci sequence is generated by adding the 
    previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...  

    By considering the terms in the Fibonacci sequence whose values 
    do not exceed four million, find the sum of the even-valued terms.
*/
int main(int argc, char const *argv[])
{
    int i;
    int temp = 2;
    int prevFib = 2;
    int prevFib2 = 1;
    for(i = 3; i < 4000000; i++)
    {
        if(i == prevFib + prevFib2){
            
            if(i % 2 == 0)
            {
                temp += i;
            }

            prevFib2 = prevFib;
            prevFib = i;
            i += prevFib2 - 1;
        }
    }

     printf("The total of the even fibonacci numbers under 4000000 is %d\n", temp);
    
    return 0;
}
